services:
  db:
    image: postgres:15
    container_name: ticketing_postgres
    environment:
      POSTGRES_USER: app_user_pg
      POSTGRES_PASSWORD: ticketing
      POSTGRES_DB: ticketing_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user_pg -d ticketing_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: src/main/java/com/ticketingportal/Dockerfile
    container_name: ticketing_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ticketing_db
      SPRING_DATASOURCE_USERNAME: app_user_pg
      SPRING_DATASOURCE_PASSWORD: ticketing
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
